modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="kratos.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="pack.png"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.fps_horizon]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.fps_horizon]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.fps_horizon]]
modId="embeddium"
mandatory=true
versionRange="[0.3.31,)"
ordering="NONE"
side="CLIENT"
